import React, { useState } from 'react';
import { Package, Loader2, Lock, Download, Hash, Video, Zap } from 'lucide-react';
import { generateCampaignPack } from '../services/analysis';
import { CampaignPack } from '../types/analysis';

interface CampaignPackExporterProps {
  onUpgradeClick: () => void;
  hasUsedFreeTrial: boolean;
}

const CampaignPackExporter: React.FC<CampaignPackExporterProps> = ({ onUpgradeClick, hasUsedFreeTrial }) => {
  const [niche, setNiche] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [campaignPack, setCampaignPack] = useState<CampaignPack | null>(null);

  const handleGenerate = async () => {
    if (!niche.trim()) return;
    
    if (hasUsedFreeTrial) {
      onUpgradeClick();
      return;
    }

    setIsGenerating(true);
    try {
      const result = await generateCampaignPack(niche);
      setCampaignPack(result);
    } catch (error) {
      console.error('Error generating campaign pack:', error);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleDownload = () => {
    if (!campaignPack) return;

    const content = `
CAMPAIGN PACK FOR ${campaignPack.niche.toUpperCase()}
Generated: ${new Date(campaignPack.generatedAt).toLocaleDateString()}

=== TWITTER/X POSTS ===
${campaignPack.tweets.map((tweet, i) => `${i + 1}. ${tweet}`).join('\n')}

=== TIKTOK HOOKS ===
${campaignPack.tiktokHooks.map((hook, i) => `${i + 1}. ${hook}`).join('\n')}

=== AD CAPTIONS ===
${campaignPack.adCaptions.map((caption, i) => `${i + 1}. ${caption}`).join('\n')}

---
Generated by AdRocket AI
    `;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `campaign-pack-${campaignPack.niche.replace(/\s+/g, '-').toLowerCase()}-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <section className="px-6 py-12">
      <div className="max-w-6xl mx-auto">
        <div className="text-center mb-8">
          <h2 className="text-3xl font-bold text-white mb-4">
            One-Click Campaign Pack
          </h2>
          <p className="text-gray-400">
            Generate 30 pieces of content: 10 tweets, 10 TikTok hooks, 10 ad captions
          </p>
        </div>

        {!campaignPack ? (
          <div className="max-w-2xl mx-auto">
            <div className="bg-gray-800/50 backdrop-blur-sm border border-gray-700/50 rounded-xl p-8">
              <div>
                <label className="text-white font-medium mb-2 block">Your Niche</label>
                <input
                  type="text"
                  value={niche}
                  onChange={(e) => setNiche(e.target.value)}
                  placeholder="e.g., fitness coaching, digital marketing, real estate..."
                  className="w-full bg-gray-900/50 border border-gray-600 rounded-lg px-4 py-3 text-white 
                           placeholder-gray-400 focus:border-yellow-400 focus:outline-none"
                />
              </div>
              
              <button
                onClick={handleGenerate}
                disabled={isGenerating || !niche.trim()}
                className="w-full mt-6 px-6 py-4 bg-gradient-to-r from-yellow-400 to-amber-500 text-black 
                         font-bold rounded-lg hover:from-yellow-300 hover:to-amber-400 transition-all duration-300 
                         shadow-lg shadow-yellow-400/25 hover:shadow-yellow-400/40 disabled:opacity-50 
                         disabled:cursor-not-allowed flex items-center justify-center space-x-2"
              >
                {isGenerating ? (
                  <>
                    <Loader2 className="w-5 h-5 animate-spin" />
                    <span>Generating 30 Pieces of Content...</span>
                  </>
                ) : hasUsedFreeTrial ? (
                  <>
                    <Lock className="w-5 h-5" />
                    <span>Unlock Campaign Pack - $9.99/mo</span>
                  </>
                ) : (
                  <>
                    <Package className="w-5 h-5" />
                    <span>Generate Campaign Pack</span>
                  </>
                )}
              </button>
              
              {!hasUsedFreeTrial && (
                <p className="text-center text-gray-400 text-sm mt-3">
                  ✨ Free trial • No credit card required
                </p>
              )}
            </div>
          </div>
        ) : (
          <div className="space-y-8 animate-fade-in">
            {/* Header with Download */}
            <div className="text-center bg-gray-800/50 backdrop-blur-sm border border-gray-700/50 rounded-xl p-6">
              <h3 className="text-2xl font-bold text-white mb-4">
                🎉 Campaign Pack Ready for {campaignPack.niche}!
              </h3>
              <button
                onClick={handleDownload}
                className="px-6 py-3 bg-gradient-to-r from-yellow-400 to-amber-500 text-black font-semibold 
                         rounded-lg hover:from-yellow-300 hover:to-amber-400 transition-all duration-300 
                         flex items-center space-x-2 mx-auto"
              >
                <Download className="w-4 h-4" />
                <span>Download Complete Pack</span>
              </button>
            </div>

            {/* Content Grid */}
            <div className="grid lg:grid-cols-3 gap-6">
              {/* Twitter Posts */}
              <div className="bg-gray-800/50 backdrop-blur-sm border border-gray-700/50 rounded-xl p-6">
                <div className="flex items-center space-x-2 mb-4">
                  <Hash className="w-5 h-5 text-blue-400" />
                  <h4 className="text-blue-400 font-bold text-lg">Twitter/X Posts</h4>
                </div>
                <div className="space-y-3 max-h-96 overflow-y-auto">
                  {campaignPack.tweets.map((tweet, index) => (
                    <div key={index} className="bg-gray-900/50 rounded-lg p-3">
                      <div className="flex justify-between items-start mb-2">
                        <span className="text-blue-400 font-semibold text-sm">#{index + 1}</span>
                        <span className="text-gray-500 text-xs">{tweet.length}/280</span>
                      </div>
                      <p className="text-gray-300 text-sm">{tweet}</p>
                    </div>
                  ))}
                </div>
              </div>

              {/* TikTok Hooks */}
              <div className="bg-gray-800/50 backdrop-blur-sm border border-gray-700/50 rounded-xl p-6">
                <div className="flex items-center space-x-2 mb-4">
                  <Video className="w-5 h-5 text-pink-400" />
                  <h4 className="text-pink-400 font-bold text-lg">TikTok Hooks</h4>
                </div>
                <div className="space-y-3 max-h-96 overflow-y-auto">
                  {campaignPack.tiktokHooks.map((hook, index) => (
                    <div key={index} className="bg-gray-900/50 rounded-lg p-3">
                      <div className="flex justify-between items-start mb-2">
                        <span className="text-pink-400 font-semibold text-sm">#{index + 1}</span>
                        <span className="text-gray-500 text-xs">Hook</span>
                      </div>
                      <p className="text-gray-300 text-sm">{hook}</p>
                    </div>
                  ))}
                </div>
              </div>

              {/* Ad Captions */}
              <div className="bg-gray-800/50 backdrop-blur-sm border border-gray-700/50 rounded-xl p-6">
                <div className="flex items-center space-x-2 mb-4">
                  <Zap className="w-5 h-5 text-green-400" />
                  <h4 className="text-green-400 font-bold text-lg">Ad Captions</h4>
                </div>
                <div className="space-y-3 max-h-96 overflow-y-auto">
                  {campaignPack.adCaptions.map((caption, index) => (
                    <div key={index} className="bg-gray-900/50 rounded-lg p-3">
                      <div className="flex justify-between items-start mb-2">
                        <span className="text-green-400 font-semibold text-sm">#{index + 1}</span>
                        <span className="text-gray-500 text-xs">Ad</span>
                      </div>
                      <p className="text-gray-300 text-sm">{caption}</p>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            {/* Usage Guide */}
            <div className="bg-gray-800/50 backdrop-blur-sm border border-gray-700/50 rounded-xl p-6">
              <h4 className="text-yellow-400 font-bold text-lg mb-4">📋 How to Use Your Campaign Pack</h4>
              <div className="grid md:grid-cols-3 gap-6">
                <div>
                  <h5 className="text-blue-400 font-semibold mb-2">Twitter/X Strategy</h5>
                  <ul className="text-gray-300 text-sm space-y-1">
                    <li>• Post 1-3 tweets daily</li>
                    <li>• Schedule during peak hours</li>
                    <li>• Engage with replies quickly</li>
                    <li>• Use relevant hashtags</li>
                  </ul>
                </div>
                <div>
                  <h5 className="text-pink-400 font-semibold mb-2">TikTok Strategy</h5>
                  <ul className="text-gray-300 text-sm space-y-1">
                    <li>• Use hooks as video openers</li>
                    <li>• Create 15-60 second videos</li>
                    <li>• Add trending sounds</li>
                    <li>• Post consistently daily</li>
                  </ul>
                </div>
                <div>
                  <h5 className="text-green-400 font-semibold mb-2">Ad Strategy</h5>
                  <ul className="text-gray-300 text-sm space-y-1">
                    <li>• A/B test different captions</li>
                    <li>• Use for Facebook/Instagram ads</li>
                    <li>• Pair with compelling visuals</li>
                    <li>• Track performance metrics</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        )}
      </div>
    </section>
  );
};

export default CampaignPackExporter;