import React, { useState } from 'react';
import { FileImage, Loader2, Lock, Copy, Download, Palette, Type, Layout } from 'lucide-react';
import { createInfographic } from '../services/moreFeatures';
import { InfographicWizard as InfographicWizardType } from '../types/moreFeatures';

interface InfographicWizardProps {
  onUpgradeClick: () => void;
  hasUsedFreeTrial: boolean;
}

const InfographicWizard: React.FC<InfographicWizardProps> = ({ onUpgradeClick, hasUsedFreeTrial }) => {
  const [topic, setTopic] = useState('');
  const [isCreating, setIsCreating] = useState(false);
  const [infographic, setInfographic] = useState<InfographicWizardType | null>(null);

  const handleCreate = async () => {
    if (!topic.trim()) return;
    
    if (hasUsedFreeTrial) {
      onUpgradeClick();
      return;
    }

    setIsCreating(true);
    try {
      const result = await createInfographic(topic);
      setInfographic(result);
    } catch (error) {
      console.error('Error creating infographic:', error);
    } finally {
      setIsCreating(false);
    }
  };

  const handleCopy = (text: string) => {
    navigator.clipboard.writeText(text);
  };

  const handleDownload = () => {
    if (!infographic) return;

    let content = `
MONETIZABLE INFOGRAPHIC WIZARD
=============================
Generated: ${new Date().toLocaleDateString()}

TOPIC
----
${infographic.topic}

INFOGRAPHIC DESIGN
----------------
Headline: ${infographic.infographic.headline}
Subheadline: ${infographic.infographic.subheadline}

Layout: ${infographic.infographic.layout}
Color Scheme: ${infographic.infographic.colorScheme}
Font Pairings: ${infographic.infographic.fontPairings}

SECTIONS
-------
${infographic.infographic.sections.map((section, i) => 
  `Section ${i + 1}: ${section.title}
Content: ${section.content}
Icon Suggestion: ${section.iconSuggestion}`
).join('\n\n')}

SOCIAL MEDIA
----------
Caption: ${infographic.caption}
CTA: ${infographic.cta}

MONETIZATION
----------
Angle: ${infographic.monetizationAngle}
Lead Magnet Idea: ${infographic.leadMagnetIdea}

---
Generated by NexusAI
    `;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `infographic-${topic.replace(/\s+/g, '-').toLowerCase()}-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <section className="px-6 py-12">
      <div className="max-w-6xl mx-auto">
        <div className="text-center mb-8">
          <h2 className="text-3xl font-bold text-white mb-4">
            Monetizable Infographic Wizard
          </h2>
          <p className="text-gray-400">
            Create viral-style infographics with monetization angles and CTAs
          </p>
        </div>

        {!infographic ? (
          <div className="max-w-2xl mx-auto">
            <div className="bg-gray-800/50 backdrop-blur-sm border border-gray-700/50 rounded-xl p-8">
              <div>
                <label className="text-white font-medium mb-2 block">Infographic Topic</label>
                <input
                  type="text"
                  value={topic}
                  onChange={(e) => setTopic(e.target.value)}
                  placeholder="e.g., 7 productivity hacks, social media marketing tips, healthy eating guide..."
                  className="w-full bg-gray-900/50 border border-gray-600 rounded-lg px-4 py-3 text-white 
                           placeholder-gray-400 focus:border-yellow-400 focus:outline-none"
                />
              </div>
              
              <button
                onClick={handleCreate}
                disabled={isCreating || !topic.trim()}
                className="w-full mt-6 px-6 py-4 bg-gradient-to-r from-yellow-400 to-amber-500 text-black 
                         font-bold rounded-lg hover:from-yellow-300 hover:to-amber-400 transition-all duration-300 
                         shadow-lg shadow-yellow-400/25 hover:shadow-yellow-400/40 disabled:opacity-50 
                         disabled:cursor-not-allowed flex items-center justify-center space-x-2"
              >
                {isCreating ? (
                  <>
                    <Loader2 className="w-5 h-5 animate-spin" />
                    <span>Creating Infographic...</span>
                  </>
                ) : hasUsedFreeTrial ? (
                  <>
                    <Lock className="w-5 h-5" />
                    <span>Unlock Infographic Wizard - $9.99/mo</span>
                  </>
                ) : (
                  <>
                    <FileImage className="w-5 h-5" />
                    <span>Create Infographic</span>
                  </>
                )}
              </button>
              
              {!hasUsedFreeTrial && (
                <p className="text-center text-gray-400 text-sm mt-3">
                  ✨ Free trial • No credit card required
                </p>
              )}
            </div>
          </div>
        ) : (
          <div className="space-y-8 animate-fade-in">
            {/* Header with Download */}
            <div className="text-center bg-gray-800/50 backdrop-blur-sm border border-gray-700/50 rounded-xl p-6">
              <h3 className="text-2xl font-bold text-white mb-4">
                🖼️ Infographic for {infographic.topic}
              </h3>
              <button
                onClick={handleDownload}
                className="px-6 py-3 bg-gradient-to-r from-yellow-400 to-amber-500 text-black font-semibold 
                         rounded-lg hover:from-yellow-300 hover:to-amber-400 transition-all duration-300 
                         flex items-center space-x-2 mx-auto"
              >
                <Download className="w-4 h-4" />
                <span>Download Infographic Design</span>
              </button>
            </div>

            {/* Infographic Header */}
            <div className="bg-gray-800/50 backdrop-blur-sm border border-gray-700/50 rounded-xl p-6">
              <div className="flex justify-between items-start mb-4">
                <h4 className="text-yellow-400 font-bold text-lg">📝 Infographic Header</h4>
                <button
                  onClick={() => handleCopy(`${infographic.infographic.headline}\n\n${infographic.infographic.subheadline}`)}
                  className="p-2 text-gray-400 hover:text-white transition-colors"
                >
                  <Copy className="w-4 h-4" />
                </button>
              </div>
              <div className="space-y-4">
                <div className="bg-gray-900/50 rounded-lg p-4">
                  <h5 className="text-white font-semibold mb-2">Headline</h5>
                  <p className="text-gray-300 text-lg">{infographic.infographic.headline}</p>
                </div>
                <div className="bg-gray-900/50 rounded-lg p-4">
                  <h5 className="text-white font-semibold mb-2">Subheadline</h5>
                  <p className="text-gray-300">{infographic.infographic.subheadline}</p>
                </div>
              </div>
            </div>

            {/* Design Elements */}
            <div className="grid md:grid-cols-3 gap-6">
              <div className="bg-gray-800/50 backdrop-blur-sm border border-gray-700/50 rounded-xl p-6">
                <div className="flex items-center space-x-3 mb-4">
                  <Layout className="w-6 h-6 text-blue-400" />
                  <h4 className="text-blue-400 font-bold text-lg">Layout</h4>
                </div>
                <div className="bg-blue-500/10 border border-blue-500/20 rounded-lg p-4">
                  <p className="text-gray-300 text-sm">{infographic.infographic.layout}</p>
                </div>
              </div>
              
              <div className="bg-gray-800/50 backdrop-blur-sm border border-gray-700/50 rounded-xl p-6">
                <div className="flex items-center space-x-3 mb-4">
                  <Palette className="w-6 h-6 text-purple-400" />
                  <h4 className="text-purple-400 font-bold text-lg">Color Scheme</h4>
                </div>
                <div className="bg-purple-500/10 border border-purple-500/20 rounded-lg p-4">
                  <p className="text-gray-300 text-sm">{infographic.infographic.colorScheme}</p>
                </div>
              </div>
              
              <div className="bg-gray-800/50 backdrop-blur-sm border border-gray-700/50 rounded-xl p-6">
                <div className="flex items-center space-x-3 mb-4">
                  <Type className="w-6 h-6 text-green-400" />
                  <h4 className="text-green-400 font-bold text-lg">Typography</h4>
                </div>
                <div className="bg-green-500/10 border border-green-500/20 rounded-lg p-4">
                  <p className="text-gray-300 text-sm">{infographic.infographic.fontPairings}</p>
                </div>
              </div>
            </div>

            {/* Content Sections */}
            <div className="bg-gray-800/50 backdrop-blur-sm border border-gray-700/50 rounded-xl p-6">
              <h4 className="text-yellow-400 font-bold text-lg mb-4">📊 Content Sections</h4>
              <div className="space-y-4">
                {infographic.infographic.sections.map((section, index) => (
                  <div key={index} className="bg-gray-900/50 rounded-lg p-4">
                    <div className="flex justify-between items-start mb-2">
                      <h5 className="text-white font-semibold">Section {index + 1}: {section.title}</h5>
                      <button
                        onClick={() => handleCopy(`${section.title}\n\n${section.content}`)}
                        className="p-1 text-gray-400 hover:text-white transition-colors"
                      >
                        <Copy className="w-3 h-3" />
                      </button>
                    </div>
                    <p className="text-gray-300 text-sm mb-3">{section.content}</p>
                    <div className="bg-blue-500/10 border border-blue-500/20 rounded-lg p-2">
                      <p className="text-blue-400 text-xs">Icon Suggestion: {section.iconSuggestion}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Social Media & Monetization */}
            <div className="grid md:grid-cols-2 gap-6">
              <div className="bg-gray-800/50 backdrop-blur-sm border border-gray-700/50 rounded-xl p-6">
                <div className="flex justify-between items-start mb-4">
                  <h4 className="text-pink-400 font-bold text-lg">📱 Social Media</h4>
                  <button
                    onClick={() => handleCopy(`${infographic.caption}\n\n${infographic.cta}`)}
                    className="p-2 text-gray-400 hover:text-white transition-colors"
                  >
                    <Copy className="w-4 h-4" />
                  </button>
                </div>
                <div className="space-y-4">
                  <div className="bg-gray-900/50 rounded-lg p-4">
                    <h5 className="text-white font-semibold mb-2">Caption</h5>
                    <p className="text-gray-300 text-sm">{infographic.caption}</p>
                  </div>
                  <div className="bg-pink-500/10 border border-pink-500/20 rounded-lg p-4">
                    <h5 className="text-pink-400 font-semibold mb-2">Call to Action</h5>
                    <p className="text-gray-300 text-sm">{infographic.cta}</p>
                  </div>
                </div>
              </div>
              
              <div className="bg-gray-800/50 backdrop-blur-sm border border-gray-700/50 rounded-xl p-6">
                <h4 className="text-green-400 font-bold text-lg mb-4">💰 Monetization</h4>
                <div className="space-y-4">
                  <div className="bg-gray-900/50 rounded-lg p-4">
                    <h5 className="text-white font-semibold mb-2">Monetization Angle</h5>
                    <p className="text-gray-300 text-sm">{infographic.monetizationAngle}</p>
                  </div>
                  <div className="bg-green-500/10 border border-green-500/20 rounded-lg p-4">
                    <h5 className="text-green-400 font-semibold mb-2">Lead Magnet Idea</h5>
                    <p className="text-gray-300 text-sm">{infographic.leadMagnetIdea}</p>
                  </div>
                </div>
              </div>
            </div>

            {/* Design & Promotion Tips */}
            <div className="bg-gray-800/50 backdrop-blur-sm border border-gray-700/50 rounded-xl p-6">
              <h4 className="text-yellow-400 font-bold text-lg mb-4">📋 Design & Promotion Tips</h4>
              <div className="grid md:grid-cols-2 gap-6">
                <div>
                  <h5 className="text-white font-semibold mb-3">Design Best Practices</h5>
                  <ul className="text-gray-300 text-sm space-y-2">
                    <li>• Use consistent spacing (8px grid system)</li>
                    <li>• Limit to 3-5 colors from your palette</li>
                    <li>• Use icons from the same style family</li>
                    <li>• Maintain text hierarchy (3 sizes max)</li>
                    <li>• Add your branding subtly but clearly</li>
                    <li>• Ensure high contrast for readability</li>
                  </ul>
                </div>
                <div>
                  <h5 className="text-white font-semibold mb-3">Promotion Strategy</h5>
                  <ul className="text-gray-300 text-sm space-y-2">
                    <li>• Post on Pinterest with keyword-rich description</li>
                    <li>• Share on LinkedIn with industry insights</li>
                    <li>• Create carousel version for Instagram</li>
                    <li>• Add to relevant Facebook groups with question</li>
                    <li>• Email to your list with exclusive bonus</li>
                    <li>• Create blog post expanding on infographic</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        )}
      </div>
    </section>
  );
};

export default InfographicWizard;