import { AdResult, CampaignDay } from '../types/ad';
import { InfluencerPitchResult } from '../types/influencer';

export const downloadAdPackage = (ad: AdResult) => {
  const content = `
VIRAL AD PACKAGE
================
Generated: ${new Date().toLocaleDateString()}
Tone: ${ad.tone || 'Professional'}

HEADLINE
--------
${ad.headline}

AD COPY
-------
${ad.adCopy}

TIKTOK SCRIPT
-------------
${ad.tiktokScript}

CAPTION VARIATIONS
------------------
${ad.captions.map((caption, i) => `${i + 1}. ${caption}`).join('\n')}

PERFORMANCE ESTIMATES
--------------------
${ad.performanceEstimate ? `
Engagement Rate: ${ad.performanceEstimate.engagementRate}%
Click-Through Rate: ${ad.performanceEstimate.clickThroughRate}%
Conversion Rate: ${ad.performanceEstimate.conversionRate}%
` : 'Performance estimates not available'}

BUSINESS TYPE
-------------
${ad.businessType}

---
Generated by AdRocket AI
  `;
  
  downloadTextFile(content, `viral-ad-package-${Date.now()}.txt`);
};

export const downloadCampaignPackage = (campaign: CampaignDay[]) => {
  const content = `
7-DAY VIRAL CAMPAIGN PACKAGE
============================
Generated: ${new Date().toLocaleDateString()}

${campaign.map(day => `
DAY ${day.day}: ${day.theme.toUpperCase()}
${'='.repeat(day.theme.length + 10)}

HEADLINE: ${day.headline}

AD COPY:
${day.adCopy}

TIKTOK SCRIPT:
${day.tiktokScript}

CAPTIONS:
${day.captions.map((caption, i) => `${i + 1}. ${caption}`).join('\n')}

${'─'.repeat(50)}
`).join('')}

---
Generated by AdRocket AI
  `;
  
  downloadTextFile(content, `7-day-campaign-${Date.now()}.txt`);
};

export const downloadInfluencerPitch = (pitch: InfluencerPitchResult) => {
  const content = `
INFLUENCER PITCH PACKAGE
========================
Generated: ${new Date().toLocaleDateString()}
Influencer Tier: ${pitch.influencerTier}
Niche: ${pitch.niche}

OUTREACH MESSAGE
----------------
${pitch.outreachMessage}

FOLLOW-UP MESSAGES
------------------
${pitch.followUpMessages.map((msg, i) => `
Follow-up #${i + 1}:
${msg}
`).join('')}

PITCH DECK
----------

Brand Overview:
${pitch.pitchDeck.brandOverview}

Partnership Benefits:
${pitch.pitchDeck.benefits.map((benefit, i) => `${i + 1}. ${benefit}`).join('\n')}

Content Ideas:
${pitch.pitchDeck.contentIdeas.map((idea, i) => `${i + 1}. ${idea}`).join('\n')}

Compensation:
${pitch.pitchDeck.compensation}

Next Steps:
${pitch.pitchDeck.nextSteps}

---
Generated by AdRocket AI
  `;
  
  downloadTextFile(content, `influencer-pitch-${Date.now()}.txt`);
};

const downloadTextFile = (content: string, filename: string) => {
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};